### ISSUE TITLE
.htaccess Inconsistencies

### ISSUE THREAD

**Issue by mustafauysal** [poweredcache/powered-cache#101]
See: https://wordpress.org/support/topic/inconsistencies-in-generated-htaccess-file/

**Comment by AndisGrossteins** [comment]
Just checking in from WordPress.org to subscribe to this issue.

I looked at the code which generates the `.htaccess` rules. I think it would be beneficial to have a more granular and structured control of MIME types and respective browser caching rules. Same structured array could then be used to generate `AddType`, `ExpiresByTeype`, and `AddOutputFilterByType` rules.
