### ISSUE TITLE
PHP 8.2 Deprecations

### ISSUE THREAD

**Issue by mustafauysal** [poweredcache/powered-cache#120]
Creation of dynamic property is deprecated in PHP 8.2 we should avoid using them in object cache drop-ins

**Comment by mustafauysal** [comment]
see: https://github.com/Automattic/wp-memcached/pull/149/commits

**Comment by mustafauysal** [comment]
Drop-ins updated; if the problem persists, `pecl-memcache` extension needs to be updated - https://github.com/websupport-sk/pecl-memcache/pull/104

**Comment by mustafauysal** [comment]
Hi @Igor-Yworld 

Yes, you will need to update `pecl-memcache` extension.

**Comment by Igor-Yworld** [comment]
Thanks @mustafauysal, but I still don't fully understand, is there already a new version of pecl-memcache or is it not ready yet?

**Comment by mustafauysal** [comment]
Yes, a new version is ready that addresses the problem with the extension - https://pecl.php.net/package/memcache

To determine your current extension version, you can run either `php -i` or `phpinfo()`. I encountered a similar issue in my test environment, which was due to using the 4.x version of the extension.

**Comment by mustafauysal** [comment]
fixed in f776ac69dc777cc969785cc528f3e008e512bcad
