### ISSUE TITLE
redis password

### ISSUE THREAD

**Issue by joksik** [poweredcache/powered-cache#141]
I noticed that when I have a password defined in Redis, the plugin cannot connect to the database I have error "**Redis Connection error, please check the credentials!"**
In file /etc/redis/redis.conf i have enable **requirepass** and restart redis service. After that plugin poweredcache informs me that it cannot connect to the database.
In file **wp-config.php** i define password with define('WP_REDIS_PASSWORD',        'mysecretpassword');
i also check other plugins for Wordpress like Redis Object Cache and with the password option enabled, the plugin connects to the database without any problems. so most likely my settings in redis.conf  and wp-config.php are correct.
PS: when i remove password option from /etc/redis/redis.conf plugin poweredcache can connect to the database ;) but for security reasons I would like to use a password when making connections :/.

![redis](https://github.com/poweredcache/powered-cache/assets/11992667/10c43d71-169c-461d-aafe-b3b3e9d8a548)

**Comment by mustafauysal** [comment]
Hi @joksik

Please read the documentation here - https://docs.poweredcache.com/object-caching/#redis

You can define credentials by passing the `auth` key to global $redis_server. 

eg: 
```
$redis_server = array( 'host' => '127.0.0.1', 'port' => 6379, 'auth' => 'yourAuthPass', 'database' => 0 );

``

and add this line of code to your wp-config.php file

**Comment by joksik** [comment]
ok, you have right, before i try **password** instead **auth**

**Comment by mustafauysal** [comment]
ok, I think everything is alright now. Closing the issue.
