### ISSUE TITLE
WPbakery

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#64]
This option is not showing when is installed WPbakery editor. 
https://docs.poweredcache.com/disable-page-caching-for-specific-posts/

**Comment by mustafauysal** [comment]
@dusta Can you add a screenshot? and check the console logs? 

Do you see the options when not using WPBaker' editing mode?

**Comment by mustafauysal** [comment]
I assume the problem is solved, closing this issue now, feel free to re-open if the latest version didn't work for you.
