### ISSUE TITLE
Server Side Tracking with Page Cache

### ISSUE THREAD

**Issue by razvanFrandes** [poweredcache/powered-cache#69]
Hello,

The plugin works great ! well done.

I have a question :
How can I hook into powered cache plugin to execute a function to send data about the user into segment.
I use segment for server side tracking, no JavaScript. 

For example : when user does a request do : myFunction() { // get user data }, + return the cached html page.

Thank you.

**Comment by mustafauysal** [comment]
Hi @razvanFrandes, 

I'm not sure if I understand the question correctly. If you need to partially cache a part of a page, using fragment caching might be a better solution. 

https://github.com/poweredcache/powered-cache/blob/master/includes/utils.php#L1042-L1052

**Comment by razvanFrandes** [comment]
Hi @mustafauysal,

Forget what is said.
I don't know how page caching is working. 

To be more simple,
For example I have the website fully page-cached. How do I call a function before the cached page is served.
I tried some hooks on this page https://poweredcache.github.io/docs/.
ex: add_action('powered_cache_loaded', 'myFunction');

Is it possible to do something before the page is served to the client ? Or the cached page is served trough .htaccess and not php.


Thank you :)

**Comment by mustafauysal** [comment]
Hi @razvanFrandes,

> Is it possible to do something before the page is served to the client ? Or the cached page is served trough .htaccess and not php.

If the server is compatible with `.htaccess` the cached results are served without executing PHP at all. (You can disable this option)

> ex: add_action('powered_cache_loaded', 'myFunction');

This is not possible even with the cached results served via PHP. WordPress loads `advanced-cache.php` (the responsible part of page caching) way earlier than the plugin's API.

**Comment by razvanFrandes** [comment]
Hi @mustafauysal ,

Thank you :)

I did manage to add in htaccess this " php_value auto_prepend_file  " which can execute a php function.

Thank you again, I learned something today.

Have a great day.

**Comment by mustafauysal** [comment]
You're welcome @razvanFrandes,

> I did manage to add in htaccess this " php_value auto_prepend_file " which can execute a php function.

It depends on how you wanna utilize the function. You can also include a custom PHP with `wp-config.php` too, but the WP related functions will not be available before bootstrapping phase.


Have a great day too, I'm closing this issue now.
