### ISSUE TITLE
CDN Add Hostname

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#74]
There is no action after enable and click "Add Hostname". 
Also in console there is no errors. 

![obraz](https://user-images.githubusercontent.com/9001348/155109064-aea27d5b-1fd3-451c-aab0-43a7cf3fd7fb.png)

**Comment by dusta** [comment]
There is no element with that ID. Only one I see is:

<div id="cdn-zones" class="sui-form-field"></div>
and its empty.

**Comment by mustafauysal** [comment]
@dusta Thanks for checking it. 

It seems somehow `cdn_hostname` saved as empty (instead of an empty array). Resetting plugin settings should restore it back. I will fix this in the next version.

**Comment by dusta** [comment]
@mustafauysal  Working. Thanks :)
