### ISSUE TITLE
CDN .htaccess generate 

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#79]
This need to add to htaccess when cdn is enable. If not you have  forbidden CORS „Access-Control-Allow-Origin”)

```code

<FilesMatch "\.(ttf|otf|eot|woff|woff2)$">
    <IfModule mod_headers.c>
        SetEnvIf Origin "http(s)?://(www\.)?(____CDN)URL__)$" AccessControlAllowOrigin=$0
        Header set Access-Control-Allow-Origin "*"
    </IfModule>
</FilesMatch>

```

**Comment by mustafauysal** [comment]
@dusta I'm not sure why did you close this issue. It seems a good catch. The next version will include the automatic CORS rules when CDN integration is enabled.
