### ISSUE TITLE
Sitemap cache

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#83]
**Feature** - Add option cache sitemap with **separate time cache**

**Comment by mustafauysal** [comment]
@dusta what do you mean? Can you explain a little more?

**Comment by dusta** [comment]
I have added in the settings to keep the page cache of 1 month. My sitemap is set to 50k records. I would like to set the sitemap cache to refresh every 2-3 days

**Comment by mustafauysal** [comment]
@dusta Powered Cache doesn't do caching or control the files with the `.xml` extension. And, I don't recommend refreshing the sitemap 2-3 days.

if you are using Yoast SEO to create the sitemap, maybe something like - https://markjaquith.wordpress.com/2018/01/22/how-i-fixed-yoast-seo-sitemaps-on-a-large-wordpress-site/ is a better solution for you?

**Comment by dusta** [comment]
@mustafauysal These aren't exactly .xml files. Wordpress index.php is so it displays them as .xml On the website I manage, 10-20k pages can change in one day. Thats why I need dynamic sitemap
