### ISSUE TITLE
Preload selected taxonomy

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#84]
**Feature** - Preload selected taxonomy

For example I have over 100k post in one taxonomy, preload all post eat all my server resources. Good option is select what taxonomy will have preload

**Comment by mustafauysal** [comment]
@dusta Actually, preloading functionality doesn't preload all the posts. It just preloads the latest 1000 posts. You can adjust the number with `powered_cache_preload_post_limit` filter.


And there is another filter for limiting the taxonomies that will be preloaded `powered_cache_preload_taxonomies`. It preloads the most used 100 terms by default. And you can adjust the term numbers with `powered_cache_preload_term_limit` filter.


I might be better to control, but I'd like to keep things simple most of the time. Do these hooks work for you? You can check hook reference if need more details - https://poweredcache.github.io/docs/

**Comment by dusta** [comment]
Preload is done via cron? If so, how often ?

**Comment by mustafauysal** [comment]
@dusta it's done with async background processing - https://github.com/deliciousbrains/wp-background-processing

When you trigger the preloading from the admin bar, it will queue to preload items, and then whenever the cached results are removed, it generates automatically. (expired cache cleanups done via cron)

Expired cache cleanups work hourly if you enter TTL more than an hour - (https://github.com/poweredcache/powered-cache/blob/2.1.1/includes/classes/Cron.php#L113-L122)

Here is detail about preloading functionality - https://docs.poweredcache.com/enable-preloading/

**Comment by mustafauysal** [comment]
Closing this issue.
