### ISSUE TITLE
Cache folder regexp

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#88]
Can you add option that allow put own regexp option for cache location?

**Comment by mustafauysal** [comment]
@dusta Why would you need regex support for the location? Could you give more context?

**Comment by dusta** [comment]
Folder structure is to small and in 1 folder have over 100k subfolders and cannot enter in this location. I need split by some schema

examples schema url websites 

this-is-some-url-page-71726373
This-is-some/url-page/717282
717282/This-is-some/url-page
Category/This-is-some-717282

I need make from this structure like this

This/is/some/url/page/71726373
This/is-some/url/page/717282
7/1/7/2/8/2/This-is-some/url-page
Category/This-is-some/717282
